{
	"version": 1699527355,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/bat-sheet0.png",
		"images/background-sheet0.png",
		"images/bottompipe-sheet0.png",
		"images/toppipe-sheet0.png",
		"images/flash-sheet0.png",
		"images/ground-sheet0.png",
		"images/jumplocation-sheet0.png",
		"images/destroyer-sheet0.png",
		"images/playdn-sheet0.png",
		"images/toppipeautomove-sheet0.png",
		"images/bottompipeautomove-sheet0.png",
		"images/downblock-sheet0.png",
		"images/touchlocation-sheet0.png",
		"images/moregames-sheet0.png",
		"images/speakers-sheet0.png",
		"images/speakers-sheet1.png",
		"images/gametitle-sheet0.png",
		"images/wall-sheet0.png",
		"images/wall2-sheet0.png",
		"images/bt_twitter-sheet0.png",
		"media/flappy1-1.m4a",
		"media/flappy1-1.ogg",
		"media/flappy2-1.m4a",
		"media/flappy2-1.ogg",
		"media/pickup_coin (7).m4a",
		"media/pickup_coin (7).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}